// Supabase client + ideas CRUD
// Loaded after supabase-config.js (which is generated by build.js)

(function () {
  'use strict';

  const DELETE_PASS = window.DELETE_PASSWORD || 'Ethan Can Hack';

  // ── Init ──────────────────────────────────────────────────────────────────
  const url = window.SUPABASE_URL;
  const key = window.SUPABASE_PUBLISHABLE_KEY;

  let db = null;
  if (url && key) {
    db = window.supabase.createClient(url, key);
  } else {
    console.warn('Supabase not configured — ideas form is offline-only.');
  }

  // ── Helpers ───────────────────────────────────────────────────────────────
  function safeHtml(str) {
    const d = document.createElement('div');
    d.textContent = String(str);
    return d.innerHTML;
  }

  function setFormBusy(busy) {
    const btn = document.querySelector('#req-form button[type="submit"]');
    if (btn) btn.disabled = busy;
  }

  // ── CRUD ──────────────────────────────────────────────────────────────────
  async function fetchIdeas() {
    if (!db) return [];
    const { data, error } = await db
      .from('ideas')
      .select('id, name, idea, created_at')
      .order('created_at', { ascending: true });
    if (error) { console.error('fetchIdeas:', error); return []; }
    return data;
  }

  async function insertIdea(name, idea) {
    const { data, error } = await db
      .from('ideas')
      .insert({ name, idea })
      .select()
      .single();
    if (error) throw error;
    return data;
  }

  async function removeIdea(id) {
    const { error } = await db
      .from('ideas')
      .delete()
      .eq('id', id);
    if (error) throw error;
  }

  // ── Render ────────────────────────────────────────────────────────────────
  async function renderIdeas() {
    const list = document.getElementById('req-list');
    if (!list) return;
    list.innerHTML = '<p class="req-empty">Loading…</p>';
    const ideas = await fetchIdeas();
    list.innerHTML = '';
    if (!ideas.length) {
      list.innerHTML = '<p class="req-empty">No ideas yet — be the first.</p>';
      return;
    }
    ideas.forEach(function (item) {
      const div = document.createElement('div');
      div.className = 'req-item';
      div.innerHTML =
        '<span class="req-who">'  + safeHtml(item.name) + '</span>' +
        '<span class="req-text">' + safeHtml(item.idea) + '</span>' +
        '<button class="req-delete" data-id="' + item.id + '" title="Delete idea">🗑️</button>';
      list.appendChild(div);
    });
  }

  // ── Form submit ───────────────────────────────────────────────────────────
  document.getElementById('req-form').addEventListener('submit', async function (e) {
    e.preventDefault();
    if (!db) { alert('Supabase is not configured yet.'); return; }
    const name = this.elements['name'].value;
    const idea = this.elements['idea'].value.trim();
    if (!name || !idea) return;
    setFormBusy(true);
    try {
      await insertIdea(name, idea);
      await renderIdeas();
      this.reset();
    } catch (err) {
      console.error('submit:', err);
      alert('Could not save your idea — try again.');
    } finally {
      setFormBusy(false);
    }
  });

  // ── Delete modal ──────────────────────────────────────────────────────────
  const delModal   = document.getElementById('del-modal');
  const delInput   = document.getElementById('del-password');
  const delError   = document.getElementById('del-error');
  const delConfirm = document.getElementById('del-confirm');
  const delCancel  = document.getElementById('del-cancel');
  const delBackdrop = document.getElementById('del-backdrop');
  let pendingDeleteId = null;
  let pendingDeleteBtn = null;

  function openDelModal(id, btn) {
    pendingDeleteId  = id;
    pendingDeleteBtn = btn;
    delInput.value   = '';
    delError.hidden  = true;
    delModal.hidden  = false;
    delInput.focus();
  }

  function closeDelModal() {
    delModal.hidden  = true;
    pendingDeleteId  = null;
    pendingDeleteBtn = null;
  }

  delCancel.addEventListener('click', closeDelModal);
  delBackdrop.addEventListener('click', closeDelModal);

  delInput.addEventListener('keydown', function (e) {
    if (e.key === 'Enter') delConfirm.click();
    if (e.key === 'Escape') closeDelModal();
  });

  delConfirm.addEventListener('click', async function () {
    const pass = delInput.value;
    if (pass !== DELETE_PASS) {
      delError.hidden = false;
      delInput.value = '';
      delInput.focus();
      return;
    }
    delConfirm.disabled = true;
    delConfirm.textContent = 'Deleting…';
    try {
      await removeIdea(pendingDeleteId);
      closeDelModal();
      await renderIdeas();
    } catch (err) {
      console.error('delete:', err);
      delError.textContent = 'Could not delete — try again.';
      delError.hidden = false;
    } finally {
      delConfirm.disabled = false;
      delConfirm.textContent = 'Delete';
    }
  });

  document.getElementById('req-list').addEventListener('click', function (e) {
    const btn = e.target.closest('.req-delete');
    if (!btn) return;
    openDelModal(btn.dataset.id, btn);
  });

  // ── Boot ──────────────────────────────────────────────────────────────────
  renderIdeas();
})();
