// Reads vars from .env (local) or process.env (Vercel) and writes js/supabase-config.js
// Run locally:  node build.js
// On Vercel:    runs automatically before each deploy

const fs = require('fs');

// ── Auto-load .env locally (no dotenv package needed) ──────────────────────
if (fs.existsSync('.env')) {
  fs.readFileSync('.env', 'utf8').split('\n').forEach(line => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) return;
    const eq = trimmed.indexOf('=');
    if (eq === -1) return;
    const k = trimmed.slice(0, eq).trim();
    const v = trimmed.slice(eq + 1).trim();
    if (!process.env[k]) process.env[k] = v; // don't override real env vars
  });
}

// ── Read vars ───────────────────────────────────────────────────────────────
const url  = process.env.SUPABASE_URL             || '';
const key  = process.env.SUPABASE_PUBLISHABLE_KEY || '';
const pass = process.env.DELETE_PASSWORD          || '';

if (!url || !key) {
  console.warn('⚠  SUPABASE_URL or SUPABASE_PUBLISHABLE_KEY not set — ideas form will be disabled.');
}

// ── Write config ─────────────────────────────────────────────────────────────
fs.mkdirSync('js', { recursive: true });
fs.writeFileSync(
  'js/supabase-config.js',
  `// Auto-generated by build.js — do not edit or commit this file\n` +
  `window.SUPABASE_URL             = '${url}';\n` +
  `window.SUPABASE_PUBLISHABLE_KEY = '${key}';\n` +
  `window.DELETE_PASSWORD          = '${pass}';\n`
);

console.log('✓ js/supabase-config.js written');

